name: AI BGM Bot

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - run: sudo apt install ffmpeg

    - run: pip install -r requirements.txt

    - run: |
        git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui
        cd stable-diffusion-webui
        ./webui.sh --api --nowebui &
        sleep 120

    - name: Run bot
      env:
        SUNO_COOKIE: ${{ secrets.SUNO_COOKIE }}
        YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
        YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
        YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
      run: python bot.py
