"""
YouTube自動投稿スクリプト

機能:
    - YouTube Data API v3 を使用
    - OAuth 2.0 refresh token で認証
    - 動画のアップロードとメタデータ設定
"""

import os
import sys
from pathlib import Path
from datetime import datetime
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

OUTPUT_DIR = Path("output")

def get_youtube_client():
    """YouTube API クライアントを取得"""
    
    # 環境変数から認証情報を取得
    client_id = os.getenv('YOUTUBE_CLIENT_ID')
    client_secret = os.getenv('YOUTUBE_CLIENT_SECRET')
    refresh_token = os.getenv('YOUTUBE_REFRESH_TOKEN')
    
    if not all([client_id, client_secret, refresh_token]):
        print("❌ YouTube API の認証情報が設定されていません")
        print("GitHub Secrets に以下を設定してください:")
        print("  - YOUTUBE_CLIENT_ID")
        print("  - YOUTUBE_CLIENT_SECRET")
        print("  - YOUTUBE_REFRESH_TOKEN")
        sys.exit(1)
    
    # 認証情報オブジェクト作成
    credentials = Credentials(
        None,
        refresh_token=refresh_token,
        token_uri="https://oauth2.googleapis.com/token",
        client_id=client_id,
        client_secret=client_secret
    )
    
    # YouTube API クライアント作成
    youtube = build('youtube', 'v3', credentials=credentials)
    
    return youtube

def read_metadata():
    """メタデータから情報を取得"""
    today = datetime.now().strftime('%Y-%m-%d')
    metadata_file = OUTPUT_DIR / f"{today}_metadata.txt"
    
    metadata = {}
    if metadata_file.exists():
        with open(metadata_file, 'r', encoding='utf-8') as f:
            for line in f:
                if ':' in line:
                    key, value = line.split(':', 1)
                    metadata[key.strip()] = value.strip()
    
    return metadata

def create_video_metadata(prompt):
    """動画のメタデータを作成"""
    
    # タイトル生成
    today = datetime.now().strftime('%Y/%m/%d')
    title = f"🎵 {prompt.title()} | 60 Min Chill BGM for Study/Work/Relax [{today}]"
    
    # 説明文生成
    description = f"""
🎵 {prompt.title()} - 60 Minutes Chill Background Music

Perfect for studying, working, relaxing, or just chilling out.
This music was generated using AI (ACE-Step 1.5) and is copyright-free.

🎧 Tracklist:
00:00 - {prompt.title()}

📝 Tags:
#lofi #chillmusic #studymusic #bgm #relaxing #ambient #peaceful

🤖 Generated by AI BGM BOT
Music: ACE-Step 1.5
Background: Stable Diffusion

📅 Upload Date: {today}

---

⚠️ Copyright Notice:
This music is AI-generated and free to use.
Feel free to enjoy it for personal use.

💖 Thank you for listening!
Please subscribe for more chill music 🔔
""".strip()
    
    # タグ
    tags = [
        'lofi', 'chill', 'bgm', 'study music', 'work music',
        'relaxing', 'ambient', 'peaceful', 'ai music', 'copyright free'
    ]
    
    return {
        'title': title,
        'description': description,
        'tags': tags,
        'category_id': '10',  # Music category
        'privacy_status': 'public'  # public, unlisted, or private
    }

def upload_video(youtube, video_path, thumbnail_path, metadata):
    """
    YouTubeに動画をアップロード
    
    Args:
        youtube: YouTube API クライアント
        video_path: 動画ファイルパス
        thumbnail_path: サムネイルパス
        metadata: 動画メタデータ
    """
    print(f"📤 YouTube アップロード開始")
    print(f"📹 動画: {video_path}")
    print(f"🖼️  サムネイル: {thumbnail_path}")
    print(f"📝 タイトル: {metadata['title']}")
    
    try:
        # 動画のメタデータ
        body = {
            'snippet': {
                'title': metadata['title'],
                'description': metadata['description'],
                'tags': metadata['tags'],
                'categoryId': metadata['category_id']
            },
            'status': {
                'privacyStatus': metadata['privacy_status'],
                'selfDeclaredMadeForKids': False
            }
        }
        
        # 動画ファイルのアップロード
        media = MediaFileUpload(
            video_path,
            chunksize=1024*1024,  # 1MB chunks
            resumable=True
        )
        
        print("🚀 動画アップロード中...")
        request = youtube.videos().insert(
            part='snippet,status',
            body=body,
            media_body=media
        )
        
        response = None
        while response is None:
            status, response = request.next_chunk()
            if status:
                progress = int(status.progress() * 100)
                print(f"📊 アップロード進捗: {progress}%")
        
        video_id = response['id']
        print(f"✅ 動画アップロード完了！")
        print(f"🎬 動画ID: {video_id}")
        print(f"🔗 URL: https://www.youtube.com/watch?v={video_id}")
        
        # サムネイルのアップロード
        if thumbnail_path.exists():
            print("🖼️  サムネイルアップロード中...")
            youtube.thumbnails().set(
                videoId=video_id,
                media_body=MediaFileUpload(thumbnail_path)
            ).execute()
            print("✅ サムネイルアップロード完了！")
        
        return video_id
        
    except Exception as e:
        print(f"❌ YouTubeアップロードエラー: {e}")
        return None

def main():
    """メイン処理"""
    print("=" * 60)
    print("📤 YouTube 自動投稿")
    print("=" * 60)
    
    # ファイルパス
    today = datetime.now().strftime('%Y-%m-%d')
    video_path = OUTPUT_DIR / f"{today}_video.mp4"
    thumbnail_path = OUTPUT_DIR / f"{today}_thumbnail.jpg"
    
    # ファイル存在確認
    if not video_path.exists():
        print(f"❌ 動画ファイルが見つかりません: {video_path}")
        sys.exit(1)
    
    # メタデータ取得
    metadata_dict = read_metadata()
    prompt = metadata_dict.get('prompt', 'Chill BGM')
    
    # YouTube メタデータ作成
    video_metadata = create_video_metadata(prompt)
    
    # YouTube クライアント取得
    youtube = get_youtube_client()
    
    # 動画アップロード
    video_id = upload_video(youtube, video_path, thumbnail_path, video_metadata)
    
    if video_id:
        print("")
        print("✅ YouTube投稿完了！")
        print(f"🎬 動画ID: {video_id}")
        print(f"🔗 URL: https://www.youtube.com/watch?v={video_id}")
        print("")
    else:
        print("❌ YouTube投稿に失敗しました")
        sys.exit(1)

if __name__ == '__main__':
    main()
